env:
  JDK_VERSION: ${{ inputs.JDK_VERSION || '11' }}
jobs:
  avd-cache-update:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Enable KVM group perms
      run: 'echo ''KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"''
        | sudo tee /etc/udev/rules.d/99-kvm4all.rules

        sudo udevadm control --reload-rules

        sudo udevadm trigger --name-match=kvm

        '
    - continue-on-error: true
      name: Set up JDK ${{ env.JDK_VERSION }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ env.JDK_VERSION }}
    - continue-on-error: true
      id: avd-cache
      name: AVD cache
      uses: actions/cache@v4
      with:
        key: avd-${{ matrix.api-level }}
        path: '~/.android/avd/*

          ~/.android/adb*

          '
    - continue-on-error: true
      if: steps.avd-cache.outputs.cache-hit != 'true'
      name: create AVD and generate snapshot for caching
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        disable-animations: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          -camera-back none
        force-avd-creation: false
        script: echo "Generated AVD snapshot for caching."
        target: google_apis
    strategy:
      matrix:
        api-level:
        - 26
        - 29
        - 30
name: Build AVD cache
on:
  repository_dispatch:
    types: trigger-ga___avd-build-and-cache.yml
