env:
  MASTER_BRANCH: master
  RELEASE_BRANCH: release
  REPO: https://${{secrets.ACTION_SECRET}}@github.com/cgeo/cgeo.git
jobs:
  merge-branches:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone and setup the repo
      run: 'git clone ${{env.REPO}} -b ${{env.MASTER_BRANCH}} tmp

        cd tmp

        git config --local include.path ../.gitconfig

        git config user.name cgeo branch-merge-bot

        git config user.email 61464155+cgeo-ci-bot@users.noreply.github.com

        '
    - continue-on-error: true
      name: Merge branches and push
      run: "cd tmp    # path is reseted for every step, therefore we need to set it\
        \ again \ngit merge origin/${{env.RELEASE_BRANCH}} -m \"merge branch '${{env.RELEASE_BRANCH}}'\
        \ via workflow\"\ngit push\n"
name: Auto-merge branches
on:
  repository_dispatch:
    types: trigger-ga___branch-merge.yml
